spring:
  application:
    name: eureka-cli-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
  instance:
    prefer-ip-address: true
logging:
  level:
    org.springframwork.cloud.gateway: debug
