server:
  port: 8010
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
  instance:
    prefer-ip-address: true
spring:
  application:
    name: eureka-cli-consumer
feign:
  hystrix:
    enabled: true
